In [1]:
import tensorflow as tf

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\saivi\\anaconda3\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


A tensor is a generalization of vectors and matrices to potentially higher dimentions. Internally, TensorFlow represents tensors as n-dimentional arrays of base datatype.

In [3]:
import numpy as np


In [4]:
# scalar or rank 0 tensor. A scalar contains a single value and no axes
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
# vector or rank 1 tensor is like list of values. has one axis.
rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [6]:
# matrix or rank 2 tensor has 2 axes
rank_2_tensor = tf.constant([[1,2],
                            [3,4],
                            [5,6]], dtype=tf.float16)
# if want to be specific, you can set the dtype at creation time
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [7]:
# There can be an arbitrary number of axes (sometimes called 'dimensions')
rank_3_tensor = tf.constant([[[0,1,2,3,4],
                             [5,6,7,8,9]],
                            [[10,11,12,13,14],
                            [15,16,17,18,19]],
                            [[20,21,22,23,24],
                            [25,26,27,28,29]]])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [8]:
# to convert a tensor to a NumPy array
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [9]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [10]:
''' Tensors contains floats, ints, complex numbers and strings.
base tf.Tensor class requires tensors to be rectangular

'''

' Tensors contains floats, ints, complex numbers and strings.\nbase tf.Tensor class requires tensors to be rectangular\n\n'

In [11]:
# basic math on tensors
a = tf.constant([[1,2],
                [3,4]])
b = tf.constant([[1,1],
                [1,1]])

In [12]:
print(tf.add(a,b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [13]:
print(tf.multiply(a,b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [14]:
print(tf.matmul(a,b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [15]:
print(a+b) # element wise addition

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [16]:
print(a * b) # element wise multiplication

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [17]:
print(a @ b) #matrix multiplication

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [18]:
c = tf.constant([[4.0,5.0],[10.0,1.0]])

In [19]:
# Find the largest value
print(tf.reduce_max(c))

tf.Tensor(10.0, shape=(), dtype=float32)


In [20]:
#Find the index of the largest value
print(tf.math.argmax(c))

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [21]:
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [22]:
'''Typically, anywhere a TensorFlow function expects a Tensor as input, 
the function will also accept anything that can be converted to a Tensor '''

'Typically, anywhere a TensorFlow function expects a Tensor as input, \nthe function will also accept anything that can be converted to a Tensor '

In [23]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [24]:
tf.reduce_max([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [25]:
tf.reduce_max(np.array([1,2,3]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

Tensors have shapes. Some vocabulary:

Shape: The length (number of elements) of each of the axes of a tensor.

Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.

Axis or Dimension: A particular dimension of a tensor.

Size: The total number of items in the tensor, the product of the shape vector's elements.

In [26]:
rank_4_tensor = tf.zeros([3,2,4,5])

In [27]:
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [28]:
print('Type of every element: ', rank_4_tensor.dtype)

Type of every element:  <dtype: 'float32'>


In [29]:
print('Number of axes: ',rank_4_tensor.ndim)
# .ndim don't return Tensor objects

Number of axes:  4


In [30]:
print("Shape of tensor: ",rank_4_tensor.shape)
# .shape don't return Tensor objects

Shape of tensor:  (3, 2, 4, 5)


In [31]:
print("Elements along axis 0 of tensor: ",rank_4_tensor.shape[0])

Elements along axis 0 of tensor:  3


In [32]:
print("Elements along the last axis of tensor: ", rank_4_tensor.shape[-1])

Elements along the last axis of tensor:  5


In [33]:
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Total number of elements (3*2*4*5):  120


In [34]:
# to ger tensor output (Number of axes)
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [35]:
# Shape of tensor
tf.shape(rank_4_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5])>

In [36]:
rank_1_tensor = tf.constant([0,1,2,3,4,5,6,7,8,9])
print(rank_1_tensor.numpy())

[0 1 2 3 4 5 6 7 8 9]


In [37]:
# indexing with a scalar removes the axis
print('First:',rank_1_tensor[0].numpy())

First: 0


In [38]:
print('second: ',rank_1_tensor[1].numpy())

second:  1


In [39]:
print('Last: ',rank_1_tensor[-1].numpy())

Last:  9


In [40]:
#Indexing with a : slice keeps the axis
print("Everything: ", rank_1_tensor[:].numpy())

Everything:  [0 1 2 3 4 5 6 7 8 9]


In [41]:
print('Before 4: ', rank_1_tensor[:4].numpy())

Before 4:  [0 1 2 3]


In [42]:
print('Reversed: ',rank_1_tensor[::-1].numpy())

Reversed:  [9 8 7 6 5 4 3 2 1 0]


In [43]:
# Multi-axis indexing
# Higher rank tensors are indexed by passing multiple indices.

#The exact same rules as in the single-axis case apply to each axis independently.

In [44]:
print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [45]:
print(rank_2_tensor[1][1].numpy())

4.0


In [46]:
print('Second row: ', rank_2_tensor[1][:].numpy())

Second row:  [3. 4.]


In [47]:
print('Second column: ', rank_2_tensor[:,1].numpy())

Second column:  [2. 4. 6.]


In [48]:
print('Last row: ', rank_2_tensor[2,:].numpy())

Last row:  [5. 6.]


In [49]:
print("Skip the first row: ", rank_2_tensor[1:].numpy())

Skip the first row:  [[3. 4.]
 [5. 6.]]


In [50]:
# 3-axis tensor
print(rank_3_tensor.numpy())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [51]:
print(rank_3_tensor[1,1,4].numpy())

19


In [52]:
print(rank_3_tensor[:,:,4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


In [53]:
# Manipulating Shapes

In [54]:
# Shape returns a "TensorShape" object that shows the size along each axis
x = tf.constant([[1],[2],[3]])
print(x.shape)

(3, 1)


In [55]:
# Convertr the shape object to python list
print(x.shape.as_list())

[3, 1]


In [56]:
# Reshape a tensor
reshaped = tf.reshape(x,[1,3])

In [57]:
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [58]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [59]:
# flattening a tensor you can see what order it is laid out in memory
#A -1 passed in the shape argument says "Whatever fits"
print(tf.reshape(rank_3_tensor,[-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [60]:
# tf.shape is to combine or split adjacent axes
print(tf.reshape(rank_3_tensor, [3*2, 5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [61]:
print(tf.reshape(rank_3_tensor, [3,-1]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


In [62]:
# Swapping axes through tf.transpose

## dtypes  

To inspect a tf.Tensor's data type use the Tensor.dtype property.

When creating a tf.Tensor from a Python object you may optionally specify the datatype.

If you don't, TensorFlow chooses a datatype that can represent your data. TensorFlow converts Python integers to tf.int32 and Python floating point numbers to tf.float32. Otherwise TensorFlow uses the same rules NumPy uses when converting to arrays.

In [63]:
f64_tensor = tf.constant([2.2,3.3,4.4], dtype = tf.float64)
f16_tensor = tf.cast(f64_tensor, dtype=tf.float16)
u8_tensor = tf.cast(f16_tensor, dtype=tf.uint8)

In [64]:
print(f64_tensor)

tf.Tensor([2.2 3.3 4.4], shape=(3,), dtype=float64)


In [65]:
print(f16_tensor)

tf.Tensor([2.2 3.3 4.4], shape=(3,), dtype=float16)


In [66]:
print(u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


## Broadcasting

When you attempt to multiply or add a tensor to a scalar, the scalar is broadcasted to be the same shape as the other argument.

In [67]:
x = tf.constant([1,2,3])
y = tf.constant(2)
z = tf.constant([2,2,2])

In [68]:
# All of these are the same computation
print(tf.multiply(x,2))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [69]:
print(x*y)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [70]:
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [71]:
# Likewise, axes with length 1 can be stretched out to match the other 
# arguments. Both arguments can be stretched in the same computation.
#In this case a 3x1 matrix is element-wise multiplied by a 1x4 matrix to 
# produce a 3x4 matrix. Note how the leading 1 is optional: The shape of y is [4].
x = tf.reshape(x, [3,-1])
y = tf.range(1,5)

In [72]:
print(x)
print('\n')
print(y)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [73]:
print(tf.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [74]:
#Most of the time, broadcasting is both time and space efficient, 
# as the broadcast operation never materializes the expanded tensors in memory.
